<a href="https://colab.research.google.com/github/a-ma-n/STC_DS_TASKS_aman/blob/master/weatherSTC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predictions

### Data Analysis

In [ ]:
import seaborn as sns
import numpy as np
import pandas as pd

weather=pd.read_csv('final stc')


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
weather.keys()

Index(['Unnamed: 0', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm',
       'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am',
       'Cloud3pm', 'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
weather['Sunshine'][55:100]
#weather.RainTomorrow.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)
#weather.RainToday.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)

55    0.0
56    0.0
57    0.0
58    0.0
59    0.0
60    0.0
61    0.0
62    0.0
63    0.0
64    0.0
65    0.0
66    0.0
67    0.0
68    0.0
69    0.0
70    0.0
71    0.0
72    0.0
73    0.0
74    0.0
75    0.0
76    0.0
77    0.0
78    0.0
79    0.0
80    0.0
81    0.0
82    0.0
83    0.0
84    0.0
85    0.0
86    0.0
87    0.0
88    0.0
89    0.0
90    0.0
91    0.0
92    0.0
93    0.0
94    0.0
95    0.0
96    0.0
97    0.0
98    0.0
99    0.0
Name: Sunshine, dtype: float64

In [ ]:
#dummy=pd.get_dummies(weather['RainTomorrow'])
#weather['RainTomorrow']

### Fitting

In [ ]:
from sklearn.model_selection import train_test_split
#weather.drop(labels=['Date','Location','WindDir9am','WindGustDir','WindDir3pm'],axis=1,inplace=True)
#weather.drop(labels=['WindDir9am'],axis=1,inplace=True)
weather.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)
#weather.RainToday.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)

weather=weather.fillna(0)

X=weather.drop('RainTomorrow',axis=1)
y=weather['RainTomorrow']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)
#

In [ ]:
X_train

Unnamed: 0  MinTemp MaxTemp  ...  Temp9am Temp3pm  RainToday
85837        85837     10.5    15.6  ...     12.3    15.1        1.0
165864      165864      4.1    13.3  ...      8.5    12.7        1.0
2130          2130     17.7    33.7  ...     25.2    32.5        0.0
220629      220629     13.4    20.3  ...     16.1    18.4        0.0
88849        88849      8.3      17  ...     12.1    15.5        0.0
...            ...      ...     ...  ...      ...     ...        ...
174979      174979     23.7    30.1  ...     26.8    29.5        1.0
56546        56546     15.1    24.4  ...     20.7    19.6        0.0
187657      187657     10.5    24.7  ...     15.5    24.1        0.0
53707        53707     12.4    22.7  ...     19.0    20.9        0.0
82301        82301     21.1      27  ...     23.4    26.7        1.0

[165668 rows x 18 columns]

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

logmodel.fit(X_train,y_train)

predictions = logmodel.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

ValueError: ignored

## **K-nearest Neighbours**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


*choosing k value*

In [ ]:
error_rate = []

for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))
    


ValueError: ignored

In [ ]:
error_rate

In [ ]:
error_rate.index(min(error_rate))

In [ ]:
knn = KNeighborsClassifier(n_neighbors=34)

knn.fit(X_train,y_train)
pred = knn.predict(X_test)

print('WITH K=34')
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

## Desicion tree

In [ ]:
X_train

Unnamed: 0  MinTemp MaxTemp  ...  Temp9am Temp3pm  RainToday
85837        85837     10.5    15.6  ...     12.3    15.1        1.0
165864      165864      4.1    13.3  ...      8.5    12.7        1.0
2130          2130     17.7    33.7  ...     25.2    32.5        0.0
220629      220629     13.4    20.3  ...     16.1    18.4        0.0
88849        88849      8.3      17  ...     12.1    15.5        0.0
...            ...      ...     ...  ...      ...     ...        ...
174979      174979     23.7    30.1  ...     26.8    29.5        1.0
56546        56546     15.1    24.4  ...     20.7    19.6        0.0
187657      187657     10.5    24.7  ...     15.5    24.1        0.0
53707        53707     12.4    22.7  ...     19.0    20.9        0.0
82301        82301     21.1      27  ...     23.4    26.7        1.0

[165668 rows x 18 columns]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()

dtree.fit(X_train,y_train)
predictions = dtree.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

ValueError: ignored

In [ ]:
X_train.tail()

## **Random Forests**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)


In [ ]:
rfc_pred = rfc.predict(X_test)
print(confusion_matrix(y_test,rfc_pred))


In [ ]:
print(classification_report(y_test,rfc_pred))

## **SVM**


In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_model=SVC()
svc_model.fit(X_train,y_train)

ValueError: ignored

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {'C': [1, 10], 'gamma': [0.1,0.01]} 

In [ ]:
grid=GridSearchCV(SVC(),param_grid,verbose=2,refit=2)

In [ ]:
grid.fit(X_train,y_train)

In [ ]:
grid_predictions=grid.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,grid_predictions))

In [ ]:
print(classification_report(y_test,grid_predictions))

## **K means Clustering**

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2)
kmeans.fit(weather.drop('RainTomorrow',axis=1))

In [ ]:
#kmeans.cluster_centers_

In [ ]:
def converter(cluster):
    if cluster==0:
        return 0
    else:
        return 1

In [ ]:
weather['Cluster'] = weather['RainTomorrow'].apply(converter)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(weather['Cluster'],kmeans.labels_))
print(classification_report(weather['Cluster'],kmeans.labels_))

In [ ]:

weather.to_csv("final stc")

# Results:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## **Logistic regression**
[[32311  1853]
 [ 5811  3663]]


## **KNN:**

K=34

[[32726  1447]

 [ 5165  4300]]
## **Descision Trees:**
[[35711  1500]

 [ 5492  5050]]

estimators=100

## **Random Forests:**
trees=100

[[32632  1541]

 [ 4794  4671]]

## **SVM:**



## **KMeansClustering:** 

[[101460  12123]

 [ 28718   3159]]
