# Predictions

### Data Analysis

In [2]:
import seaborn as sns
import numpy as np
import pandas as pd

weather=pd.read_csv('weatherAUS.csv')


In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
weather.keys()

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [5]:
weather['RainTomorrow'][55:100]
#weather.RainTomorrow.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)
#weather.RainToday.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)

55     No
56     No
57     No
58     No
59     No
60     No
61     No
62     No
63     No
64     No
65     No
66     No
67     No
68     No
69     No
70     No
71     No
72     No
73    Yes
74     No
75     No
76     No
77     No
78     No
79     No
80     No
81     No
82     No
83     No
84     No
85     No
86     No
87     No
88     No
89     No
90     No
91     No
92     No
93     No
94     No
95     No
96     No
97     No
98     No
99    Yes
Name: RainTomorrow, dtype: object

In [6]:
dummy=pd.get_dummies(weather['RainTomorrow'])
weather['RainTomorrow']

0          No
1          No
2          No
3          No
4          No
         ... 
145455     No
145456     No
145457     No
145458     No
145459    NaN
Name: RainTomorrow, Length: 145460, dtype: object

In [7]:
weather['RainTomorrow'][0]

'No'

In [8]:
weather.head()


Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No
1  2008-12-02   Albury      7.4  ...     24.3         No            No
2  2008-12-03   Albury     12.9  ...     23.2         No            No
3  2008-12-04   Albury      9.2  ...     26.5         No            No
4  2008-12-05   Albury     17.5  ...     29.7         No            No

[5 rows x 23 columns]

### Fitting

In [9]:
from sklearn.model_selection import train_test_split
weather.drop(labels=['Date','Location','WindDir9am','WindGustDir','WindDir3pm'],axis=1,inplace=True)
#weather.drop(labels=['WindDir3pm'],axis=1,inplace=True)
weather.RainTomorrow.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)
weather.RainToday.replace(to_replace=['No', 'Yes'], value=[0, 1],inplace=True)

weather=weather.fillna(0)

X=weather.drop('RainTomorrow',axis=1)
y=weather['RainTomorrow']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)


In [ ]:
weather


## **K-nearest Neighbours**

In [15]:
from sklearn.neighbors import KNeighborsClassifier


*choosing k value*

In [11]:
error_rate = []

for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))
    


KeyboardInterrupt: ignored

In [ ]:
error_rate

In [ ]:
error_rate.index(min(error_rate))

In [ ]:
knn = KNeighborsClassifier(n_neighbors=34)

knn.fit(X_train,y_train)
pred = knn.predict(X_test)

print('WITH K=34')
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

## **Random Forests**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)


In [ ]:
rfc_pred = rfc.predict(X_test)
print(confusion_matrix(y_test,rfc_pred))


In [ ]:
print(classification_report(y_test,rfc_pred))

## **SVM**


In [10]:
from sklearn.svm import SVC

In [ ]:
svc_model=SVC()
svc_model.fit(X_train,y_train)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [13]:
param_grid = {'C': [1, 10], 'gamma': [0.1,0.01]} 

In [14]:
grid=GridSearchCV(SVC(),param_grid,verbose=2,refit=2)

In [ ]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] C=1, gamma=0.1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................... C=1, gamma=0.1, total=26.9min
[CV] C=1, gamma=0.1 ..................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 26.9min remaining:    0.0s


[CV] ................................... C=1, gamma=0.1, total=26.8min
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=26.9min
[CV] C=1, gamma=0.1 ..................................................


In [ ]:
grid_predictions=grid.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,grid_predictions))

In [ ]:
print(classification_report(y_test,grid_predictions))

## **K means Clustering**

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2)
kmeans.fit(weather.drop('RainTomorrow',axis=1))

In [ ]:
#kmeans.cluster_centers_

In [ ]:
def converter(cluster):
    if cluster==0:
        return 0
    else:
        return 1

In [ ]:
weather['Cluster'] = weather['RainTomorrow'].apply(converter)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(weather['Cluster'],kmeans.labels_))
print(classification_report(weather['Cluster'],kmeans.labels_))

# Results:



## **KNN:**

K=34

[[32726  1447]

 [ 5165  4300]]


## **Random Forests:**
trees=100

[[32632  1541]

 [ 4794  4671]]

## **SVM:**



## **KMeansClustering:** 

[[101460  12123]

 [ 28718   3159]]
